apple/swift-metrics

.swiftformat
Tests/LinuxMain.swift
Tests/MetricsTests/CoreMetricsTests+XCTest.swift
Tests/MetricsTests/MetricsTests+XCTest.swift
scripts/generate_linux_tests.rb

motivation: use consistent formatting
changes: update generate_linux_tests to match the formatting rules we use: `swiftformat --self insert --patternlet inline --stripunusedargs unnamed-only --comments ignore`

fix linux tests formatting

---

README.md

The bootstrap used to be invoked using `MyFactory.init` but nowadays we changed it to accepting an factory instance.
**Problem:**
- snippet was misleading and would not compile
**Solution:**
- change to snippet that will work with current shape of API
- make the code snippet more visible and not in-line, so it is easier to spot "so what do I need to do to bootstrap again...?"

Fix incorrect bootstrap invocation in README

---

.gitignore
README.md
Sources/CoreMetrics/Metrics.swift
Tests/MetricsTests/CoreMetricsTests+XCTest.swift
Tests/MetricsTests/CoreMetricsTests.swift
Tests/MetricsTests/TestMetrics.swift

Replaces https://github.com/apple/swift-metrics/pull/3
Resolves #2 
// And making it as new PR since I think due to some weird branch magic (since the repo I PR from does not recognize that it is a "fork" in github and I keep getting 500 pages "sometimes" when viewing the PR 3... Reported to GH support btw).
--- 
After a few rounds of feedback and ideas from everyone involved (thank you all), I think we're getting to the right balance in this API.
This version offers:
- `counter.destroy()`  (and same for all other types)
- which makes is user friendly and discoverable
- which lives "right next to `Counter.init`, which is good since both are "lifecycle",
- and both "reach to MetricsSystem" -- the global store, so it is good to have them close to one another
- `destroyCounter` and friends …

Introduce metric.destroy() to enable lifecycle management #2

---

Sources/CoreMetrics/Metrics.swift

Motivation:
API documentation contains typos and grammatical errors.
Modifications:
Fix typos and grammatical errors. Update to use code syntax where
appropriate.
Result:
Eliminate typos and grammatical errors found.

Fix API documentation

---

Sources/CoreMetrics/Metrics.swift

I noticed on a community chat that it was confusing to some that the first init they noticed was documented as "dont use this".
The specific confusion was:
- first found `init(label: String, dimensions: [(String, String)], handler: TimerHandler)` but it has docs "do not use" (correctly, as the intended one to be used is `init(label:dimensions:)`)
- next looked at the `MetricsFactory`, since seems like that's what "creates things"; but this yields the internal handlers; 
Problem: we did not lead the user to the "right" init function to use, as it is defined a bit below -- in an extension, as we wanted it there to be next to the destroy as then all lifecycle for users is in there.
- adds more see-also links
- reformats main wording that the "this is main api" etc are more visible

doc: #26 clarify which init to use, reformat docs for easier noticing this

---

Sources/CoreMetrics/Metrics.swift
Tests/MetricsTests/CoreMetricsTests+XCTest.swift
Tests/MetricsTests/CoreMetricsTests.swift

Motivation:
`Timer.record*` methods are generic to cover all cases of `BinaryInteger` values and converts the passed value into `Int64` before doing time unit conversions and overflow checks.
Modifications:
All methods that accept `BinaryInteger` types and converts to `Int64` now guards against values higher than `Int64.max`
Result:
Users can reliably use the `Timer.record*` APIs with `BinaryInteger` types without concern for unknowing fatal errors.
_[One line description of your change]_
_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_
_[Describe the modifications you've done.]_
_[After your change, what will change.]_

Add guards for Int64 overflow in `Timer` methods

---

Sources/CoreMetrics/Metrics.swift
Sources/Metrics/Metrics.swift
Tests/MetricsTests/CoreMetricsTests.swift

Motivation:
As discussed in Issue #28, there are a few preferred lightweight APIs for getting timestamps such as `DispatchTime` but those APIs return `UInt64` types, which need to be handled for overflow.
Modifications:
Added a generic `BinaryInteger` overload method for `recordNanoseconds` that guards against accidental overflows from `UInt64` to `Int64`
Result:
Users now have access to a new method to record nanosecond measurements with `Timer` that guards against overflows.

Add `Timer.recordNanoseconds` Generic Overload (#28)

---

CODE_OF_CONDUCT.md

motivation: use correct email address for conduct issues
changes: make sure email address is `swift-server-conduct@group.apple.com` everywhere

update conduct email address

---

docker/Dockerfile
docker/docker-compose.1804.42.yaml
docker/docker-compose.1804.50.yaml
docker/docker-compose.1804.51.yaml
docker/docker-compose.yaml
scripts/check_no_api_breakages.sh

motivation: better ci testing
changes:
* add api breakage script to test api breakage in ci
* add "shell" utility docker-compose task to run api breakage script
* change test task to treat warning as errors
* change test task to use thread sanitizer in 5.1

test with thread sanitizer and check for api breakage in ci

---

Sources/Metrics/Metrics.swift

As per @weissi on the Vapor discord:
You’re using wall time which isn’t right to measure how long a function ran. Imagine your CPU went to sleep or the user changed the date.
This came up in a discussion around a similar implementation in SwiftPrometheus
This PR aims to avoid scenarios where function durations are messed up due to use of wall time.
Updated `Timer.measure()` to use a delta of `DispatchTime.now().uptimeNanoseconds` instead of wall time.
Nothing for end users, although timing will no longer depend on wall time.

Update Timer.measure() to use DispatchTime instead of Date

---

Tests/MetricsTests/TestMetrics.swift

There is a typo in the test output ("recoding" vs "recording").
Fix two typos in `TestMetrics.swift`
Nicer test output :)

Fix typos in test output

---

Sources/CoreMetrics/Metrics.swift

MetricsSystem.bootstrap verifies that the metric system has not been previously
initialized. Otherwise it should fail with a corresponding error message. The
precondition error message includes the name of the currently used factory and
for that accesses self.factory. However, because bootstrap already holds
self.lock as a writer lock, self.factory fails to get it as a reader and
crashes with a less useful precondition error message.
Currently, the error message received is:
```
Precondition failed: file [...]/swift-metrics/Sources/CoreMetrics/Locks.swift, line 125
```
Use `self._factory` instead of `self.factory`.
The correct error message is printed:
```
Precondition failed: metrics system can only be initialized once per process. currently used factory: CoreMetrics.NOOPMetricsHandler: …
```

Bugfix: Print correct error message if bootstrap is called multiple times

---

Sources/CoreMetrics/Locks.swift

The `precondition` calls in Lock functions in `CoreMetrics/Locks.swift` currently do not specify an error message. These obviously should be rare but might be triggered due to other bugs.
Currently, on a precondition failure in `Locks.swift`, errors look like this:
```
Precondition failed: file [...]/swift-metrics/Sources/CoreMetrics/Locks.swift, line 125
```
Add precondition messages to the `precondition` calls in `CoreMetrics/Locks.swift`.
This commit adds error messages to the precondition checks in Lock functions
that state the action that failed as well as the OS error code.
Precondition failures in `Locks.swift` will result in a message like this:
```
Precondition failed: pthread_rwlock_rdlock failed with error 11: file [...]/swift-metrics/Sources/CoreMetrics/Locks.swift, line 125 …
```

Improve precondition error messages in Lock functions

---

Sources/CoreMetrics/Metrics.swift
Tests/MetricsTests/MetricsTests+XCTest.swift
Tests/MetricsTests/MetricsTests.swift
Tests/MetricsTests/TestMetrics.swift

Motivation:
I have a metrics backend where I need to store timer values in
microseconds. The "preferred display unit" models this exactly, but it
seems to have (inadvertently?) omitted the possibility to express
microseconds. Note that among the timer "report" methods there is
already a microseconds option.
Modifications:
adding an emum case is an API breaking change. so instead of just adding the enum case for microseconds, we use this opportunity to change `TimeUnit` from enum to struct so that we can add more cases in the future without breaking the API.

Add microseconds to the TimeUnit enum

---

README.md

Update the README to recommend using 2.x releases whilst still allowing for 1.x releases. Most packages are expected to be compatible with both 1.x and 2.x so I think that's the best we can do.

README: recommend 2.x releases

---

Sources/CoreMetrics/Metrics.swift
Tests/MetricsTests/CoreMetricsTests+XCTest.swift
Tests/MetricsTests/CoreMetricsTests.swift

In some situations one may have a Timer in hand but be unsure if that's the "right one" if developing a library or framework where metrics object creation is a bit smarter than manually ad hoc created.
It is useful to be able to print what labels a metric represents.
- better description impls
- easier to debug swift-metrics in advanced use cases

+metrics should include their labels when printed to ease debugging

---

Sources/CoreMetrics/Metrics.swift
Sources/Metrics/Metrics.swift
Tests/MetricsTests/MetricsTests+XCTest.swift
Tests/MetricsTests/MetricsTests.swift

Add a method to `Timer` allowing to record the difference between a given start `DispatchTime` and a given end `DispatchTime`, defaulting to `.now()`.
I agree with the reasoning @ktoso provided  in #79 
- Added `Timer.recordInterval` method
- Added unit test for `Timer.recordInterval`
Users recording the difference between a past timestamp and "now" will be able to simplify their code by writing:
```swift
timer.recordInterval(since: start)
```
---
Closes #79

Add Timer.recordInterval method

---

Sources/CoreMetrics/Metrics.swift

For full motivation see #61 
Adds `MetricsSystem.withReaderLock` and `MetricsSystem.withWriterLock`. This allows (third party) packages to use swift-metrics' locking without making the `Lock` types public.
This will enable easier extendibility of the swift-metrics systems

Expose lock functionality

---

README.md

Just a simple one line addition to link to OpenTelemetry which has recently added support for `swift-metrics` as an optional integration/importer.

[readme] Add OpenTelemetry to compatible libraries

---

Sources/CoreMetrics/Metrics.swift
Tests/MetricsTests/CoreMetricsTests+XCTest.swift
Tests/MetricsTests/CoreMetricsTests.swift
Tests/MetricsTests/MetricsTests.swift
Tests/MetricsTests/TestMetrics.swift

Introduce FloatingPointCounter.
It is not currently possible to record floating point values via the swift-metrics API even if the metrics backend supports it.
Adds a `FloatingPointCounter` type to allow users to accumulate non-integral metrics backed by a `FloatingPointCounterHandler`. Introduces a default implementation for creating and destroying `FloatingPointCounterHandler`s for metric backends that do not natively support floating point counters.
On such backends, `FloatingPointCounter` is backed by a `AccumulatingRoundingFloatingPointCounter` which accumulates floating point values internally and record increments to a wrapped `CounterHandler` after crossing integer boundaries.
Users can create `FloatingPointCounter`s to record floating point values and get enhanced behavior for …

Introduce FloatingPointCounter

---

Package.swift

For adopters to use `MetricsTestKit` it must be exposed as a product.

Expose `MetricsTestKit` as a product

---

Sources/CoreMetrics/Locks.swift
Sources/CoreMetrics/Metrics.swift

motivation: prepare for sendable checks (they dont work well with static state)
changes:
* abstract the MetricsSystem state into a "boxed" class that handles the locking
* adjust call sites

better abstration for MetricsSystem state

---

Sources/CoreMetrics/Metrics.swift
Sources/MetricsTestKit/TestMetrics.swift
Tests/MetricsTests/CoreMetricsTests.swift
Tests/MetricsTests/MetricsTests.swift
Tests/MetricsTests/TestSendable.swift

Remove testable import from TestMetrics. Make `handler`s public, but ensure they are not part of the public API.
Users may want to use `TestMetrics` in their own test utils that support more complex use cases. For this users should be able to compile `TestMetrics` with release settings. This is currently not possible since `TestMetrics` import `CoreMetrics` `@testable`.
`CoreMetrics` is imported `@testable` since we want to have access to the underlying `MetricHandlers`.
- Make the handlers in the metrics public, but with an underscore to keep them out of the public API commitment
- Remove `@testable` from the `CoreMetrics` import in `TestMetrics `
We can compile `TestMetrics` in release mode, without special compiler flags.

Remove testable import from TestMetrics.

---

Sources/CoreMetrics/Metrics.swift

In #109, we likely forgot to require sendability for `MetricsFactory`. Given that `MetricsFactory` is accessed through the global `MetricsSystem.factory`, it clearly must be thread safe.
- Add sendability requirement to `MetricsFactory`
`MetricsFactory` is sendable and I can remove `@preconcurrency` from my CoreMetric imports.

Make `MetricsFactory` Sendable

---

Sources/MetricsTestKit/TestMetrics.swift
Tests/MetricsTests/CoreMetricsTests.swift
Tests/MetricsTests/MetricsTests.swift
Tests/MetricsTests/TestMetrics.swift
Tests/MetricsTests/TestSendable.swift

NSUUID is a reference type. We should stay Swifty and use UUID instead.

Use UUID instead of NSUUID in MetricsTests

---

Sources/Metrics/Metrics.swift
Tests/MetricsTests/MetricsTests+XCTest.swift
Tests/MetricsTests/MetricsTests.swift
scripts/soundness.sh

This pull request adds a convenience API to `Timer` that uses Swift 5.7's `Duration`. 
I'm looking for ways to learn Swift, and it's open source ecosystem by doing, and this looked like a beginner-friendly little addition that @ktoso requested (well, a year ago) in #114.
Closes #114.
- My `@available` check looks weird, I thought `Duration` is available in Swift 5.7, but looks like it's platform-specific. Do they look okay?
- Looks like DocC should pick up the function variant automatically, but I'm happy to add example / other documentation as needed.
- `Duration` conversion to seconds / nanoseconds is lossy and looks a bit janky, but seems like that's how folks are doing it for now?

Introducing Timer.record(_ duration:), closes #114

---

Sources/CoreMetrics/Metrics.swift
scripts/check_no_api_breakages.sh

The script used in CI to diagnose API breakages is a very old copy of one from NIO. It hand-rolled the builds of the two Git trees and checked the JSON report against a hard-coded SHA. This has been misfiring recently, presumably because the format of the report has changed, even though there are no API breakages.
Here's an example, which fails when comparing `main` with `main` (yes, with itself). It errors and prints the report, which says there aren't any breakages, but the script will then exit non-zero:
```console
% docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.2204.59.yaml -p swift-metrics-api-breakage-prb run --rm shell -cl 'scripts/check_no_api_breakages.sh https://github.com/apple/swift-metrics main main'
...
==============================
ERROR: public API …
```

Update API breakage CI script

---

Sources/Metrics/Metrics.swift
Tests/MetricsTests/MetricsTests.swift

The previous signature introduced in #133 was
```swift
public func record(_ duration: Duration)
```
There was already a similar function
```swift
public func record(_ duration: DispatchTimeInterval)
```
This can cause ambiguity for the compiler when using `.` shortcuts because of an overlap in case names, e.g.
```swift
timer.record(.nanoseconds(123)) // <-- ambiguous, is this DispatchTimeInterval or Duration? 
```
This is a source breaking change, which we have released in 2.4.2
Anyone using code like `timer.record(.nanoseconds(123))`, who has a minimum platform version high enough, will encounter a compiler error on code which compiled fine in 2.4.1 and below
The fix I'm proposing is to add an argument label to the new method to avoid ambiguity, but I'm open to alternative fixes here

Change Timer.record(duration: Duration) signature to avoid source breakage

---

Sources/Metrics/Metrics.swift

resolves https://github.com/apple/swift-metrics/issues/145

fix availability of record(:Duration) API

---

Sources/CoreMetrics/Metrics.swift
Sources/MetricsTestKit/TestMetrics.swift

We were missing a few `Sendable` annotations on our public types.
This PR adds `Sendable` to the missing types.

Add missing `Sendable` annotations

---

Sources/CoreMetrics/Locks.swift
Sources/CoreMetrics/Metrics.swift
Sources/Metrics/Metrics.swift
Tests/MetricsTests/MetricsTests.swift

This PR fixes Sendability warnings present when enabling strict concurrency checking.
We want to make sure `swift-metrics` is free of concurrency bugs, and thus removing Sendability warnings is crucial.
- Fixed a couple of Sendability warnings that Xcode would report when enabling strict concurrency checking.
- Also fixed other non-Sendability-related warnings about non-exhaustive `switch`es.
`swift-metrics` is now warning-free.

Fix Sendability warnings

---

Sources/CoreMetrics/Locks.swift

This PR makes the single `import Android` addition that is needed to get this package building for Android. `skip android test` passes against the emulator after I made this one change.

Android support

---

README.md
Sources/CoreMetrics/Docs.docc/index.md

Our README claims we support 4 metric types, and then lists five. But it fails to list FloatingPointCounter, which we also support, so the real number is six.
While I was here I also fixed the DocC topic, which omitted FloatingPointCounter from the list of metrics but _also_ omitted Gauge for some weird reason.

Tell the truth about the supported metric types

---

Sources/Metrics/Metrics.swift
Tests/MetricsTests/MetricsTests.swift

This PR supersedes https://github.com/apple/swift-metrics/pull/135. The goal is to make it easier to measure asynchronous code when using `Metrics`.
This PR does:
- Deprecate the current static method for measuring synchronous code
- Add a new instance method to measure synchronous code
- Add a new instance method to measure asynchronous code

Add `Timer.measure` methods

---

Sources/Metrics/Metrics.swift

Specifically Swift 5.10 on Intel on Ubuntu Noble (24.04) has a crazy bug which leads to compilation failures in a #if compiler(>=6.0) block: swiftlang/swift#79285 .
This workaround fixes the compilation by changing the whitespace.
Fixes https://github.com/apple/swift-metrics/issues/166

Fix 5.10 compile on Ubuntu 24.04

---

Sources/CoreMetrics/Metrics.swift

In the previous PR, we noticed that these warnings seem to discourage explicit dependency injection, but it's not clear why we should be discouraging it.
Removed the warning.
N/A

Remove warnings against explicit dependency injection of the metrics factory
